export const API_URL = "https://script.google.com/a/macros/virtex.com.br/s/AKfycbzGwkbuxtSB6ca7wpEcK3LbVCiuTgvBlE54kniKqqSELHhoVX84nz7Wqds9GzH7r-v3/exec";
// export const API_URL = "https://script.google.com/macros/s/AKfycbzKEwa3hm--CT00jN0d3iwsKiGYdegC4jsGrcx2Ql0NjRxYphsHylB0DaC0RY_fFWBCig/exec";

export const USERS_DATA = [
  { email: "anderson.vtx@gmail.com", nome: "Anderson Lourenço", cidade: "Picos - PI" },
  { email: "teste@gmail.com", nome: "Técnico Teste", cidade: "Teresina - PI" },
  { email: "hamuel.vtx@gmail.com", nome: "Hamuel", cidade: "Picos - PI" },
  { email: "nadya.vtx@gmail.com", nome: "Nadya", cidade: "Picos - PI" },
  { email: "lucas.vtx@gmail.com", nome: "Lucas", cidade: "Picos - PI" },
  { email: "jailton.vtx@gmail.com", nome: "Jailton", cidade: "Picos - PI" },
  { email: "rafael.vtx@gmail.com", nome: "Rafael", cidade: "Picos - PI" },
  { email: "maria.vtx@gmail.com", nome: "Maria", cidade: "Picos - PI" },
];

export const ALLOWED_EMAILS = USERS_DATA.map(user => user.email);
export const PASSWORD = "vtx2026";

export const TABELA_PESOS = {
  "ADIANTAMENTO DE SERV.": 2,
  "ALT. PPPOE": 0.25,
  "ALT. SENHA": 1,
  "APOIO A EQUIPE": 1.5,
  "APP ESPECÍFICO": 1.7,
  "AT. IPTV": 1,
  "AT. TECNOLOGICA": 1.7,
  "AT. WIFI PLUS": 1.7,
  "AT. WIFI PLUS EMP": 2,
  "AT. WIFI PRO": 2,
  ATENUAÇÃO: 1.7,
  ATIVAÇÃO: 2,
  "ATIVAÇÃO - FIBRA + WI-FI PLUS": 3,
  "ATIVAÇÃO - RÁDIO": 2,
  "ATIVAÇÃO FIBRA + VIRTEX TV": 2.5,
  "ATIVAÇÃO PRP": 2,
  "ATV - FIBRA + TELEFONIA": 3,
  "ATV SVA": 0.5,
  "ATV WIFI PLUS EMP": 2,
  "ATV- FIBRA+WIFI PRO": 2.5,
  "CABO BAIXO": 1,
  "COLHER ASSINATURA": 0.25,
  "CONF. ROTEAD. C/ VISITA": 1.5,
  "DES. DE TELEFONIA": 0.25,
  "DES. PORTA": 0.4,
  "DES. WIFI PLUS": 0.25,
  "DESAT. BOX": 0.25,
  "EMP EQUI. ESPEC.": 1.7,
  "EMP S/ CONEXÃO": 2,
  "EMP. LENTIDÃO": 2,
  "EMP. REDE INTERNA": 2,
  "EMP. TROCA EQUIP.": 1.7,
  "EQUIP. ESPECIFICO": 1.7,
  ESCALONAMENTO: 1,
  LENTIDÃO: 2,
  "LENTIDÃO ACOMP. NOC": 2,
  "M.E": 2,
  "MAN. WIFI PRO": 2,
  "MANUTENÇÃO POP": 2,
  "ME + WIFI PLUS": 2.5,
  "ME+WIFI PLUS": 2.5,
  MIGRAÇÃO: 1.7,
  MLP: 1.5,
  MMA: 2,
  "MUD. PASSAGEM DROP": 1.5,
  "ORGANIZAÇÃO DE CABO": 1.5,
  PADRONIZAÇÃO: 0.25,
  "PÓS SERVIÇO": 1.7,
  REATIVAÇÃO: 2,
  "REC+DES. PORTA": 0.25,
  RECORRÊNCIA: 1.7,
  "RECOLHER EQUIP.": 0.4,
  "RECOLOCAR EQUIP.": 1,
  "REDE INTERNA": 2,
  "REDE LIVE": 2,
  REMANEJAMENTO: 2,
  RETENÇÃO: 2.5,
  "SEM CONEXÃO": 2,
  "SEM CONEXÃO ACOMP. NOC": 2,
  "SUP. TELEFONIA": 1.7,
  "SUP. WIFI PLUS": 1.7,
  "SUP.WIFI PLUS EMP": 1.7,
  "SUPORTE ATIVO": 1.7,
  "SUPORTE VIRTEX TV": 0.5,
  "TEL. COM PORTABILIDADE": 1,
  "TEL. SEM PORTABILIDADE": 1,
  "TESTE VELOCIDADE": 1.7,
  "TROCA DE POSTE": 4,
  "TROCA EQUIP.": 1.7,
  "VIRTEX TV COM BOX": 0.5,
  "VIRTEX TV SEM BOX": 0.5,
  "VISTORIA PRÉ-ATIVAÇÃO": 0,
  "VISTORIA WIFIPRO": 1.5,
};

export const SERVICOS_IGNORADOS = ["ALMOCO", "DESLOCAMENTO", "CHUVA", "RETIRADA DE TEMPO", "BANCO DE HORAS"];

export const TIPOS_RETIRADA = [
  "RV", "RC", "DSS", "BANCO DE HORAS", "DESLOCAMENTO", 
  "RETIRADA DE TEMPO", "CHUVA", "CANCELAMENTO", "INFRAESTRUTURA"
];